// SPDX-License-Identifier: MIT
// Copyright (c) 2017-2019 Advanced Micro Devices, Inc. All rights reserved.
//! AMD FidelityFX LPM 1.20200225 CPU setup, MIT license.
//!
//! Port of `LpmSetup`, `LpmColRgbToXyz`, `LpmMatInv3x3`, and
//! `LpmMatMul3x3` from ffx_lpm.h at
//! ed6ecd5b8963d2ec24603809b90ecfa00a1c3614.
//! The first ten upstream float4 blocks are stored unchanged as 40 floats:
//! 0: saturation/contrast; 4: tone bias/lumaT; 8: lumaT/crosstalk;
//! 12: reciprocal lumaT/con2R; 16,20: con2; 24: shoulder/lumaW;
//! 28: soft gap/conR; 32: conR/conG; 36: conB/padding.
//! Headroom scaling is the final scaleOnly operation in the WGSL shader.

type Matrix = [[f32; 3]; 3];

fn dot(a: [f32; 3], b: [f32; 3]) -> f32 {
    a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
}

fn inverse(m: Matrix) -> Matrix {
    let [x, y, z] = m;
    let i = 1.0
        / (x[0] * (y[1] * z[2] - z[1] * y[2]) - x[1] * (y[0] * z[2] - y[2] * z[0])
            + x[2] * (y[0] * z[1] - y[1] * z[0]));
    [
        [
            (y[1] * z[2] - z[1] * y[2]) * i,
            (x[2] * z[1] - x[1] * z[2]) * i,
            (x[1] * y[2] - x[2] * y[1]) * i,
        ],
        [
            (y[2] * z[0] - y[0] * z[2]) * i,
            (x[0] * z[2] - x[2] * z[0]) * i,
            (y[0] * x[2] - x[0] * y[2]) * i,
        ],
        [
            (y[0] * z[1] - z[0] * y[1]) * i,
            (z[0] * x[1] - x[0] * z[1]) * i,
            (x[0] * y[1] - y[0] * x[1]) * i,
        ],
    ]
}

fn transpose(m: Matrix) -> Matrix {
    [
        [m[0][0], m[1][0], m[2][0]],
        [m[0][1], m[1][1], m[2][1]],
        [m[0][2], m[1][2], m[2][2]],
    ]
}

fn multiply(a: Matrix, b: Matrix) -> Matrix {
    let t = transpose(b);
    a.map(|row| t.map(|column| dot(row, column)))
}

fn rgb_to_xyz(primaries: [[f32; 2]; 3]) -> Matrix {
    let m = transpose(primaries.map(|xy| [xy[0], xy[1], 1.0 - (xy[0] + xy[1])]));
    let white = [0.3127 / 0.3290, 1.0, (1.0 - (0.3127 + 0.3290)) / 0.3290];
    let scale = inverse(m).map(|row| dot(row, white));
    m.map(|row| [row[0] * scale[0], row[1] * scale[1], row[2] * scale[2]])
}

fn normalized_luma(m: Matrix) -> [f32; 3] {
    let y = m[1];
    let rcp = 1.0 / (y[0] + y[1] + y[2]);
    y.map(|component| component * rcp)
}

/// Generate LPM_CONFIG_709_2020 control blocks, with the author's Rec2020
/// sample look: HDR max=16, exposure=4, contrast=0, shoulder contrast=1,
/// saturation=(0,0,0), crosstalk=(1,.5,1/32), soft gap=1/32.
pub fn generate(_headroom: f32) -> Vec<f32> {
    let hdr_max = 16.0_f32;
    let contrast = 1.0_f32;
    let mid_in = hdr_max * 0.18 * (-4.0_f32).exp2();
    let mid_out = 0.18_f32;
    let cs = contrast;
    let z0 = -mid_in.powf(contrast);
    let z1 = hdr_max.powf(cs) * mid_in.powf(contrast);
    let z2 = hdr_max.powf(contrast) * mid_in.powf(cs) * mid_out;
    let z3 = hdr_max.powf(cs) * mid_out;
    let z4 = mid_in.powf(cs) * mid_out;
    let bias0 = -((z0 + mid_out * (z1 - z2) * (1.0 / (z3 - z4))) * (1.0 / z4));
    let bias1 = (z1 - z2) * (1.0 / (z3 - z4));
    let working = rgb_to_xyz([[0.708, 0.292], [0.170, 0.797], [0.131, 0.046]]);
    let output = rgb_to_xyz([[0.64, 0.33], [0.30, 0.60], [0.15, 0.06]]);
    let luma_w = normalized_luma(working);
    let luma_t = normalized_luma(output);
    let conversion = multiply(inverse(output), working);
    let gap = 1.0_f32 / 32.0;
    let mut data = vec![0.0; 40];
    data[0..4].copy_from_slice(&[contrast, contrast, contrast, contrast]);
    data[4..8].copy_from_slice(&[bias0, bias1, luma_t[0], luma_t[1]]);
    data[8..12].copy_from_slice(&[luma_t[2], 1.0, 0.5, 1.0 / 32.0]);
    data[12..15].copy_from_slice(&luma_t.map(|v| 1.0 / v));
    data[24..28].copy_from_slice(&[1.0, luma_w[0], luma_w[1], luma_w[2]]);
    data[28..32].copy_from_slice(&[
        gap,
        (1.0 - gap) * (1.0 / (gap * std::f32::consts::LN_2)),
        conversion[0][0],
        conversion[0][1],
    ]);
    data[32..36].copy_from_slice(&[
        conversion[0][2],
        conversion[1][0],
        conversion[1][1],
        conversion[1][2],
    ]);
    data[36..39].copy_from_slice(&conversion[2]);
    data
}

#[cfg(test)]
mod tests {
    use super::generate;

    #[test]
    #[allow(clippy::excessive_precision)] // Preserve the upstream program's decimal dump.
    fn setup_matches_compiled_amd_reference() {
        // Generated by the pinned, unmodified AMD LpmSetup compiled under
        // A_CPU, with LPM_COLORS_709_2020 and the recorded sample settings.
        let expected = [
            1.0,
            1.0,
            1.0,
            1.0,
            0.948166847,
            0.829329967,
            0.212639019,
            0.715168655,
            0.0721923038,
            1.0,
            0.5,
            0.03125,
            4.70280552,
            1.39827156,
            13.8518925,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.2627002,
            0.677998066,
            0.0593017042,
            0.03125,
            44.7235451,
            1.66049075,
            -0.587641001,
            -0.0728499293,
            -0.124550492,
            1.13289976,
            -0.00834940374,
            -0.0181507356,
            -0.100578874,
            1.11872947,
            0.0,
        ];
        for (index, (&actual, &reference)) in generate(1.0).iter().zip(&expected).enumerate() {
            assert!(
                (actual - reference).abs() < 2e-6,
                "AMD LpmSetup control[{index}]: {actual} != {reference}"
            );
        }
    }
}
